### ISSUE TITLE
j4psh connect cmd don't support to pass user:pwd as parameter

### ISSUE THREAD

**Issue by cmoulliard** [rhuss/jmx4perl#46]
This request is not supported by j4psh :  

````
j4psh
[j4psh] : connect http://admin:admin@localhost:8181/hawtio/jolokia
Invalid URL http://admin:admin@localhost:8181/hawtio/jolokia
````

The reg expression should be updated to support that  or removed - https://github.com/rhuss/jmx4perl/blob/master/lib/JMX/Jmx4Perl/J4psh/ServerHandler.pm#L43

**Comment by cmoulliard** [comment]
Some ideas to update the regex : http://stackoverflow.com/questions/27745/getting-parts-of-a-url-regex

**Comment by cmoulliard** [comment]
I will provide a PR

**Comment by cmoulliard** [comment]
https://github.com/rhuss/jmx4perl/pull/47

**Comment by rhuss** [comment]
Thanks, I applied the PR. BTW, you can use user and password also by using a preconfigured server. You only need to add a `[<Server>](http://search.cpan.org/~roland/jmx4perl/scripts/check_jmx4perl#<Server>)` into your default `~/.j4p` configuration, e.g.

````
<Server tomcat>
  Url  http://localhost:8080
  User roland
  Password s!cr!t
</Server>
````

You then can connect in j4psh with a simple "connect tomcat".

The password can be even [encrypted](http://search.cpan.org/~roland/jmx4perl/scripts/jmx4perl#encrypt).

Sorry that the documentation is so "distributed" in this case.

**Comment by cmoulliard** [comment]
Thx for the info Roland. I have done a test using our hawtio jolokia project (packaged with JBoss Fuse) but that fails if I configure the connection as such : 

````
<Server fuse>
  Url  http://localhost:8181/hawtio/jolokia/
  User admin
  Password admin
</Server>

j4psh
[j4psh] : connect fuse
403 Forbidden.
````

and works we that config 
`````
<Server fuse>
  Url  http://admin:admin@localhost:8181/hawtio/jolokia/
</Server>

j4psh
[j4psh] : connect fuse
Connected to fuse (http://admin:admin@localhost:8181/hawtio/jolokia/).
[fuse] :
````

**Comment by rhuss** [comment]
That's strange, because at the end both variants end up in the same HTTP request (with a basic authentication header `Authorization:`). 

I've set up a plain Tomcat with Jolokia and for me these two configurations both work:

````
<Server tc>
  Url  http://localhost:8080/jolokia
  User admin
  Password admin
</Server>
<Server tc2>
  Url  http://admin:admin@localhost:8080/jolokia
</Server>
````

Interestingly, when authorization fails a `401 Unauthorized` should be returned, not a `403 Forbidden`. 

Could you please give me some more details how I can reproduce the first case ?

thx ...

**Comment by cmoulliard** [comment]
I get this error when I make a test with Fuse 6.2 (https://repository.jboss.org/nexus/content/groups/ea/org/jboss/fuse/jboss-fuse-full/6.2.0.redhat-109/). You can download, unzip the project and launch it under the bin directory using ./fuse script. The line admin:admin, .... of file etc/user.properties must be first uncommented

**Comment by cmoulliard** [comment]
I get also this error with the tool httpie but curl don't return an error ` curl -v -i http://localhost:8181/hawtio/jolokia/list`

**Comment by cmoulliard** [comment]
Problem is related to a workaround added by the Fuse project supporting hawtio-web/jolokia. With curl the user agent is not authenticated against jaas realm of karaf with a cookie session but basic authentication is used. As this is not the case for httpie or j4psh agents, this is why we get a 403 error
