### ISSUE TITLE
[perl] not an error when a value is not finded

### ISSUE THREAD

**Issue by garnier-quentin** [rhuss/jmx4perl#50]
Hi,

First, great work for jolokia.

My feature would be a improvement (i think :). Right now, you can use the Request object (directly or from 'get_attributes') to get datas from Jolokia. It works very well.
But if you try to get an attribute that doesn't exist, we have an error with a java backtrace. Could we get values that exists and 'undef' for others ? An example, my request:

```perl
my $path = undef;
my $attribute = ['HeapMemoryUsage', 'NnHeapMemoryUsage'];
my $object = 'java.lang:type=Memory';
my $request = JMX::Jmx4Perl::Request->new(READ,$object,$attribute,$path);
my $response = $self->{jmx4perl}->request($request);
use Data::Dumper;
print Data::Dumper::Dumper($response);
```

I would like to have the result for 'HeapMemoryUsage' and 'undef' for the other one. I don't know if i'm clear.

**Comment by rhuss** [comment]
Since `undef` maps to a Java `null` this wouldn't make much sense here because then you can distinguish between an error (attribute does not exists) and a valid `null` value.

However, you can the behaviour you need if you use bulk requests. Your example then would read like:

````perl
my $path = undef;
my $object = 'java.lang:type=Memory';
my $req1 = JMX::Jmx4Perl::Request->new(READ,$object,"HeapMemoryUsage",$path);
my $req2 = JMX::Jmx4Perl::Request->new(READ,$object,"NnHeapMemoryUsage",$path);
my $responses = $self->{jmx4perl}->request($req1,$req2);
use Data::Dumper;
print Data::Dumper::Dumper($responses);
````

Does this help ?

**Comment by garnier-quentin** [comment]
Yes it helps. Thanks. But it does 1 call or 2 calls ? I want to limit tcp flow.
Moreover, status code 500 is a connection problem ? And 404 an attribute not found ? Do you have written the status codes and what we can have ?

**Comment by rhuss** [comment]
It's a single call (both requests are send with a single POST to the server and are dispatched there), the overhead is negligible. 

The status code in the response JSON mimics HTTP semantics, so 404 is indeed attribute not found, 500 a generic exception occurred when performing the JMX operations.

**Comment by garnier-quentin** [comment]
Thans for the response. So i'll do that.

**Comment by garnier-quentin** [comment]
I have done the change: https://github.com/centreon/centreon-plugins/commit/b12c149d287a478751954f38ab924681fdff92de

It works very well. Thanks Rhuss! A really great work.
