### ISSUE TITLE
jmx4perl list command fails when using an MBean with slashes

### ISSUE THREAD

**Issue by LionelCons** [rhuss/jmx4perl#64]
Given a Jolokia server with MBeans containing slashes, the `read` command works fine while the `list` command fails.

```
$ jmx4perl <url> search <pattern>
<domain>:foo="/a/b",bar=1
...

$ jmx4perl <url> read <domain>:foo="/a/b",bar=1
=> works fine

$ jmx4perl <url> list <domain>:foo="/a/b",bar=1
ERROR: java.lang.IllegalArgumentException : Invalid path within the MBean part given.
```

The `read` command does escape the slashes while the `list` command does not.

It is not clear to me whether this is a bug or a feature.

In addition, even with manual escaping, `jmx4perl` still fails:

```
$ jmx4perl <url> list <domain>:foo="!/a!/b",bar=1
A path can be used only for a domain name or MBean name at /usr/bin/jmx4perl line 250.
```

I can submit a patch for this latter issue.

**Comment by rhuss** [comment]
looks really like a bug. A PR would be highly appreciated. thx !

**Comment by LionelCons** [comment]
Roland, could you please confirm if manual escaping is expected or not?

If yes then my PR will only address the formatting issue...

**Comment by rhuss** [comment]
Actually, manually escaping is not expected. That's internal implementation detail of the protocol and jmx4perl should this sort of escaping transparently. So, when you specify "!/" then it will be escaped by jmx4perl like "!!!/".

**Comment by LionelCons** [comment]
Transparent escaping is not easy for the `list` command. This is because it accepts a single argument representing a path.

Consider the following example derived from https://jolokia.org/reference/html/protocol.html#escape-rules:
```
$ jmx4perl <url> list jboss.jmx:alias=jmx/rmi/RMIAdaptor/State
```

How can `jmx4perl` know where the MBean part stops and where the inner path starts?

It is much easier for the `read` command as it is invoked via:
```
$ jmx4perl <url> read jboss.jmx:alias=jmx/rmi/RMIAdaptor State
```

The cleanest solution would be to change the API to accept two arguments: the MBean (needing escaping) and the inner path (not needing escaping). But this would be a major, non backward compatible change...

**Comment by rhuss** [comment]
What's about adding a variation to list which takes a second, optional argument which could be interpreted as path. When only one argument to 'list' is given we keep the current (somewhat broken) interpretation which does not work for MBean names with `/` included.

If a second argument is given then the first part is interpreted as MBean name (with transparent escaping) and the second argument then is the inner path.

That way we would stay backwards compatible but allow for advanced use cases.

**Comment by LionelCons** [comment]
First, this would not solve my initial problem since I do not use an inner path.

Then, the `list` command would end up with a strange API with a first parameter meaning that depends on the presence of the optional second argument.

Looking at the code (https://github.com/rhuss/jmx4perl/blob/master/lib/JMX/Jmx4Perl/Request.pm#L280), the `LIST` command is the only one not having a first `mbean` argument and its definition of `path` differs from (for instance) the `READ` command since it includes the MBean part.

I'm afraid the cleanest solution is to change the API (loosing backward compatibility) and have `list`'s first argument being only the MBean, with an optional second argument for the inner path, if needed.

As a bonus, this would ensure that the output of the `search` command can be given (piped) to `read` or `list` without any escaping problems.

**Comment by rhuss** [comment]
Ok, let's change it then as the migration is trivial, too (just add a space in you command).

**Comment by LionelCons** [comment]
See https://github.com/rhuss/jmx4perl/pull/65.

I also moved the magic colon to slash conversion from `command_list` to `request_url` to get a consistent behavior when calling the `list` command from the `jmx4perl` script or from Perl via a `JMX::Jmx4Perl::Request`.
