### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by jrevillard** [rhuss/jmx4perl#70]
Hi,

Major improvements were done, mainly in the "list" command of jmx4perl. I would appreciate to have it released please :pray: 

Thx in advance,
Jérôme

**Comment by rhuss** [comment]
Sorry for the very late answer, but jmx4perl is not very well maintained. I will try to push a release now later, but at the same time going to announce a sunset of jmx4perl  (except somebody will take it over), so that this repository will be archived.

**Comment by rhuss** [comment]
Took a bit, sorry. 1.13 is out. Could be one of the last releases trigger by me ...
